site_name: SkyBlock Mod Wiki
site_url: https://sbmw.ca
site_description: >
  The SkyBlock Mod Wiki is a reference for the usage of modifications (mods for short) on Hypixel SkyBlock.
  It is intended to introduce new users to mods and be a reference to the variety of different features and settings each mod offers.
repo_name: ILikePlayingGames/SkyBlockModWiki
repo_url: https://github.com/ILikePlayingGames/SkyBlockModWiki
edit_uri: edit/main/docs
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - navigation.top
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.superfences
  - toc:
      permalink: true
nav:
  - Home: 'index.md'
  - Tutorials:
      - How to Install Mods: 'tutorials/how-to-install-mods.md'
      - How to Find Crash Reports and Logs: 'tutorials/how-to-find-crash-reports-and-logs.md'
  - Mod Lists:
      - SkyBlock Mod List: 'mod-lists/skyblock-mod-list.md'
      - General Mod List: 'mod-lists/general-mod-list.md'
  - Development:
    - Getting started with Mod Development: 'development/getting-started.md'
    
